#ifndef SRC_INSTRUCTIONS_COMMANDS_H_
#define SRC_INSTRUCTIONS_COMMANDS_H_

enum DISPATCH_AND_INTERRUPT_COMMANDS {
   INSTRUCTION = 3,
   INTERRUPT_INSTRUCTION = 4,
   INTERRUPT_FINISH_INSTRUCTION = 5
};

enum kernel_commands {
    EXECUTED_INSTRUCTION = 3,
};

#endif /* SRC_INSTRUCTIONS_COMMANDS_H_ */
